### ISSUE TITLE
Not every requests is found in case some special chars or ending

### ISSUE THREAD

**Issue by kozaka-tv** [kozaka-tv/Rocksmith-Servant#151]
Examples, where Servant could not find the song from the DB according to an RSPL request:

Guns N' Roses - Don`t Cry (Tonight)
Swallow The Sun - Swallow (Horror pt.1)
Depresszió - Itt Az Én Időm
Nirvana/Sungha Jung - Come As You Are

Probably the remove/replace all special chars code has a bug.

string_utils::remove_special_chars method probably.

Please make a test too!

**Comment by ZsannaK** [comment]
I can not change this issue status!

**Comment by kozaka-tv** [comment]
I added you to the projects. Now it should work!

**Comment by ZsannaK** [comment]
It works, thank you!

**Comment by kozaka-tv** [comment]
Added some examples in the description!

**Comment by ZsannaK** [comment]
In case, the name had a special char at the very end in the name, an extra space were added to the end of the normalised string, like:
- input: "Guns N' Roses - Don`t Cry (Tonight)"
- old result: "Guns N Roses Don t Cry Tonight "

This caused, that the compaire did not worked, so the requested song's file was not found.

New result: "Guns N Roses Don t Cry Tonight"
